### ISSUE TITLE
Experimental setup for the Low-Shot Frozen Evaluation (Table 7)

### ISSUE THREAD

**Issue by bryant1410** [facebookresearch/jepa#21]
Hey, I was wondering what the number of optimization steps (or epochs) and batch sizes are used for the Low-Shot Frozen Evaluation experiment (Table 7 in the V-JEPA paper).

Is there any other hparam different from the experiments that use the full training set?

**Comment by MidoAssran** [comment]
Yes the config file is actually identical, no need to change any hyper-parameters. You simply need to point to a different dataset `CSV` file that only lists a subset of the original K400 or SSv2 datasets.
