### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by dnnspark** [facebookresearch/jepa#32]
In this implementation of attention, the `mask` input is not used:
https://github.com/facebookresearch/jepa/blob/main/src/models/utils/modules.py#L61

Can this lead to incorrect training in V-JEPA?

**Comment by jez-moxmo** [comment]
there are 3 different image encoder models and context_encoder doesn't use masks. 
![image](https://github.com/facebookresearch/jepa/assets/126642887/d8a6e52b-8a27-4b91-bd90-764f26772108)

**Comment by dnnspark** [comment]
Yup, but in the implementation of predictor, the `mask` seems to be passed : https://github.com/facebookresearch/jepa/blob/main/src/models/predictor.py#L232

Is this implementation different from what's described in the paper?

**Comment by MidoAssran** [comment]
Hi @dnnspark, this is just for backwards compatibility with an old implementation. No bug here. If you want to submit a PR removing the mask argument from the block feel free!
