### ISSUE TITLE
typo/bug in pooler?

### ISSUE THREAD

**Issue by N0r9st** [facebookresearch/jepa#4]
Probably `enumerate(self.blocks, 1)` ?

in `attentive_pooler.py`
```py
for layer_id, layer in enumerate(1, self.blocks):
        rescale(layer.attn.proj.weight.data, layer_id + 1)
        rescale(layer.mlp.fc2.weight.data, layer_id + 1)
```

**Comment by MidoAssran** [comment]
Yes that's correct, thanks for the catch. Will update that!

In the released configs we only use one block so the issue does not appear.
